#!/bin/sh
set -eu
PATH=/usr/bin:/bin:/usr/sbin:/sbin
export PATH

fail() {
  printf '%s\n' "error: $1" >&2
  exit 1
}

[ "$#" -le 1 ] || fail "usage: Scripts/sync-cli-build-metadata.sh [--check|--write]"
mode="${1:---write}"
case "$mode" in
  --check | --write) ;;
  *) fail "usage: Scripts/sync-cli-build-metadata.sh [--check|--write]" ;;
esac

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repository_root=$(CDPATH= cd -- "${script_dir}/.." && pwd)
settings_path="${repository_root}/Apps/SAFA/Config/BuildSettings.xcconfig"
output_path="${repository_root}/Sources/SAFACLI/RuntimeBuildMetadata.generated.swift"
runtime_version=$(/usr/bin/awk '$1 == "MARKETING_VERSION" { print $3; exit }' "$settings_path")
[ -n "$runtime_version" ] || fail "MARKETING_VERSION is missing"
if ! printf '%s\n' "$runtime_version" \
  | /usr/bin/grep -Eq '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$'; then
  fail "MARKETING_VERSION must be a stable semantic version"
fi

staging_path=$(/usr/bin/mktemp "${TMPDIR:-/tmp}/safa-build-metadata.XXXXXX")
cleanup() {
  /bin/rm -f -- "$staging_path"
}
trap cleanup EXIT HUP INT TERM

printf '%s\n' \
  '// Generated by Scripts/sync-cli-build-metadata.sh; do not edit.' \
  '' \
  'enum RuntimeBuildMetadata {' \
  "    static let version = \"${runtime_version}\"" \
  '}' > "$staging_path"

if [ "$mode" = "--check" ]; then
  /usr/bin/cmp -s "$staging_path" "$output_path" \
    || fail "RuntimeBuildMetadata.generated.swift is stale; run Scripts/sync-cli-build-metadata.sh"
else
  /bin/mv "$staging_path" "$output_path"
fi
